실행을 하면 memory에 들어간다. 
variables을 나간 후에 파일 선택 후 Shutdown하는 순간 memory에서 빠져나간다. 그래서 라인이 실행이 안 되기에 에러가 난다. 


In [17]:
a = 1; print(type(a))

<class 'int'>


integer: 정수 / float : 소수점 있는 수

In [18]:
a = 1; a = float(a); print(type(a))

<class 'float'>


a의 type를 float에서 integer로 바꾸고 싶으면 int(a) 를 써서 실행하면 output이 1. 여기서 주의할 것은 a가 여전히 1.0이라는 사실이다. a가 근본적으로 바뀐 것이 아니다. 

In [19]:
a = 1.2; a = int(a); print(type(a))

<class 'int'>


string 이란 숫자가 아니라 텍스트를 말한다.
single quote, double quote 다 가능하다. 
python에서는 순서가 0에서부터 시작된다!

In [20]:
a = '123'; print(type(a)); print(a[1])

<class 'str'>
2


list : 무조건 대괄호로 쳐 있고 중간에 콤마로 구분. list 속에는 list,문자,숫자가 들어가도 된다. 


In [21]:
a = '123'; a = list(a); print(type(a)); print(a); print(a[2])

<class 'list'>
['1', '2', '3']
3


In [22]:
a = [1,'2', [3, '4']]; print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'list'>
1
2
[3, '4']


tuple은 list와 다르게 [ ] 가 아니라 ( ) 로 표현이 되고 list랑 비슷한데 변동이 비교적 어렵다고 생각하면 된다.

In [23]:
a = (1,'2', [3, '4']); print(type(a)); print(a[0]); print(a[1]); print(a[2])

<class 'tuple'>
1
2
[3, '4']


line 24는 list와 다르게 pairwise로 저장이 된다. class는 dict . 사전을 생각하면 될 듯/
print(a["a"]) 할 때 "a"의 짝궁인 apple이 나온다.

In [24]:
a =	{"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


내부적으로 tuple이 있음/
2 by 3 (2줄짜리와 3열)/
콤마를 중심으로 밑으로 쌓인다. 


In [5]:
a=[(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

import : python들이 자체적으로 가지고 있는 function은 import을 하지 않아도 된다. 하드 드라이브에 있는 것을 메모리에 받아주는 작업 

파이썬에서는 행렬을 처리해줄 수 있는 것이 없어서…/ 
행렬을 바로 쓸 수 있게 해주는 것 numpy (베이식으로 있지 않으므로 메모리로 받아와야 한다) /
directory에 모든 것을 메모리에 띄어라 : import

as np 를 쓰지 않는다면 밑에 줄이 b = numpy.array(a) 라고 써야 한다. numpy에 array라는 함수를 쓴다! np.array(a)라고 쓰면 에러가 난다. numpy 밑에 있는 array를 사용하자
근데 numpy라고 쓸 때마다 너무 기니까 줄여서 쓰고 싶을 때 as np 라고 설정을 하자


array는 matrix 비슷한 것이다. b는 array화 되는 것이다. 그래서 27번의 output과 28번의 output이 다르다. 28의 output이 행렬화. 
패키지를 import하는데 시간이 걸린다. 


In [6]:
import numpy as np
b = np.array(a)
print(b)
print(type(b))

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


2x3 와 2x3 는 행렬상 곱할 수가 없다. 
그런데 여기서 array 는 곱할 수가 있다. array는 형태만 행렬과 비슷하지 행렬은 아니라서 곱하는 것이 가능하다. 


In [7]:
print(b*b)

[[ 1  4  9]
 [ 9 64  0]]


행렬로 바꾸려면 matrix 함수를 사용하자. 

In [30]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


에러가 났다!! 행렬 곱하기가 안되므로

In [31]:
c*c

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

.T : transpose  ; numpy의 행렬이다.
    
그래서 2x3 와 3x2 가 곱해지므로 가능해진다. 


In [32]:
c*c.T

matrix([[14, 19],
        [19, 73]])

** 어떤 함수들은 특정 variable들과 묶이는 것들이 있다.

s = ‘abcdef’ 
(string을 처리할 수 있는 특정 함수들이 있지 않겠느냐? 여기다가 곱하거나 나누는 함수들은 잘 안 어울리지 않느냐? 그래서 이렇게 같이 잘 어울리는 함수들끼리 묶은 것이 객체지향 (object oriented). 이러한 grouping을 잘 해 놓은 것이 객체지향이고 이런 것을 통해서 만들어지는 것이 class) 
type(s); print(type(s))
ouput > str 
          <class ‘str’>

matrix과 associate 된 함수 중에서 하나가 T(transpose)
